var DclareApplication=function(){this.binder=new DclareDOMBinder(this);this.views={};this.visibleViewKeys="";this.attributeBase="data-d";this.transitionEnd=PrefixFree.prefixProperty("transitionEnd",!0);this.animationEnd=PrefixFree.prefixProperty("animationEnd",!0);-1<this.animationEnd.indexOf("oz")?(this.animationEnd="animationend",this.transitionEnd="transitionend"):(this.animationEnd=this.animationEnd.charAt(0).toLowerCase()+this.animationEnd.slice(1),this.transitionEnd=this.transitionEnd.charAt(0).toLowerCase()+
this.transitionEnd.slice(1))};DclareApplication.prototype.start=function(a){var c=this;this.domContainer=a?"string"==typeof a?document.querySelector(a):a:document.querySelector(".dclare-container")?document.querySelector(".dclare-container"):document.querySelector("body");window.location.hash.length?(a=window.location.hash.slice(1).split(","),$(a).each(function(){c.addView(this,!0)})):this.binder.walk()};
DclareApplication.prototype.addView=function(a,c,d,b,e){var j=this,g=a.charAt(0).toUpperCase()+a.slice(1)+"View",h=null;window[g]?h=new window[g]:(console.warn(a+" has no associated view delagate, do you want to add a script tag?"),console.warn("you'll need to create the "+g+' view in the "views" folder and add the following'),console.warn("to your page's HEAD tag"),console.warn('<script src="views/'+a+'/delegate.js">\x3c/script>'),console.warn("Here is some sample delegate code to get you going, paste this into views/"+
a+"/delegate.js:"),console.warn(g+' = function() {\n  this.key = "'+a+'";\n};\n\n'+g+'.prototype.onVisible = function() {\n  //console.log("'+a+' view on before visible called!");\n};'));var f=new DclareView(a,h,this);b&&d?(f.key=$(d).attr("id"),this.views[$(d).attr("id")]=f):this.views[a]=f;DcUtil.loadCSS("views/"+a+"/style.css",function(){$.get("views/"+a+"/view.html",function(a){f.domContainer=$(a);f.domContainer.addClass("dc-invisible");f.delegate&&(f.delegate.domContainer=f.domContainer);d&&
b?(a=$(d).attr("id"),f.domContainer.attr("id",a),$(d).replaceWith(f.domContainer)):d?$(d).append(f.domContainer):$(j.domContainer).append(f.domContainer);j.binder.walk(f.key);f.onDOMReady();c&&f.show();e&&e(f)})})};DclareApplication.prototype.removeView=function(a){this.views[a.key]=null;a.destroy()};DclareApplication.prototype.getView=function(a){if(this.views[a])return this.views[a];console.error(a+" not found! did you reference a specific id?")};
DclareApplication.prototype.showView=function(a){this.views[a.key]?this.views[a.key].show(a.params):this.addView(a.key,!0)};var DclareView=function(a,c,d){c&&(this.delegate=c,this.delegate.controller=this);this.key=a||"un-keyed-view";this.isVisible=!1;this.canAnimate=!0;this.application=d;if(this.delegate&&this.delegate.onCreate)this.delegate.onCreate()};DclareView.prototype.onDOMReady=function(){if(this.delegate&&this.delegate.onDOMReady)this.delegate.onDOMReady()};
DclareView.prototype.onBeforeVisible=function(){if(this.delegate&&this.delegate.onBeforeVisible)this.delegate.onBeforeVisible()};DclareView.prototype.onVisible=function(){this.isVisible=!0;if(this.delegate&&this.delegate.onVisible)this.delegate.onVisible()};DclareView.prototype.onBeforeInvisible=function(){if(this.delegate&&this.delegate.onBeforeInvisible)this.delegate.onBeforeInvisible()};DclareView.prototype.onInvisible=function(){this.isVisible=!1;if(this.delegate&&this.delegate.onInvisible)this.delegate.onInvisible()};
DclareView.prototype.show=function(a,c){var d=this;if(this.canAnimate&&(this.canAnimate=!1,a&&this.delegate&&(this.delegate.params=a),d.onBeforeVisible(),d.domContainer.unbind(d.application.animationEnd),this.domContainer.bind(d.application.animationEnd,function(b){b.target===d.domContainer.get(0)&&(d.domContainer.unbind(d.application.animationEnd),d.domContainer.addClass("dc-visible"),d.domContainer.removeClass("dc-animate-in"),d.canAnimate=!0,d.onVisible())}),this.domContainer.addClass("dc-animate-in"),
this.domContainer.removeClass("dc-invisible"),c)){if(window.location.hash.length){for(var b=window.location.hash.slice(1).split(","),e=!0,j=0;j<b.length;j++)if(this.key==b[j]){e=!1;break}e&&b.push(this.key)}else b=[this.key];window.location.hash=b.toString()}};
DclareView.prototype.hide=function(a){var c=this;this.canAnimate&&(this.canAnimate=!1,a&&(this.delegate.params=a),c.onBeforeInvisible(),c.domContainer.unbind(c.application.animationEnd),this.domContainer.bind(c.application.animationEnd,function(a){a.target===c.domContainer.get(0)&&(c.domContainer.addClass("dc-invisible"),c.domContainer.removeClass("dc-animate-out"),c.canAnimate=!0,c.onInvisible(),c.domContainer.unbind(c.application.animationEnd))}),this.domContainer.addClass("dc-animate-out"),this.domContainer.removeClass("dc-visible"))};
DclareView.prototype.callFunction=function(a,c,d){if(this.delegate)this.delegate[a](d,c)};DclareView.prototype.onBeforeDestroy=function(){if(this.delegate&&this.delegate.onBeforeDestroy)this.delegate.onBeforeDestroy()};DclareView.prototype.destroy=function(){this.onBeforeDestroy();$(this.domContainer).remove()};
var DclareDOMBinder=function(a){var c=this;this.walk=function(d){this.currentView=d?d:!1;d=document.querySelectorAll(["div:not(.dc-bound)["+a.attributeBase+"]","div:not(.dc-bound)["+a.attributeBase+"2]","div:not(.dc-bound)["+a.attributeBase+"3]","div:not(.dc-bound)["+a.attributeBase+"4]","div:not(.dc-bound)["+a.attributeBase+"5]"].toString());for(var b=d.length;-1<b;b--){var e=d[b];$(e).addClass("dc-bound");for(var j=["","2","3","4","5"],g=0;g<j.length;g++){var h=$(e).attr(a.attributeBase+j[g]);h&&
c.processAttribute(h,e)}}};this.processAttribute=function(a,b){var e=a.indexOf(":");if(1<e){var c=a.substring(0,e),e=a.substring(e+1),e=this.processAction(e,b);this.processDclareDirective(c,e,b,this.currentView)}else this.throwError(a,b)};this.processDclareDirective=function(d,b,e,c){var g=this;if(1<d.length){var h="click",f=d.indexOf("(")+1,l=d.indexOf(")"),k=d;-1<f&&-1<l&&(h=d.substring(f,l),k=d.slice(l+1));b.action=DcUtil.stripWhiteSpace(k);"view"==b.action.toLowerCase()?b.params&&"animate"==b.params[0]?
a.addView(b.key,!0,e,!0):a.addView(b.key,!1,e,!0):(DcUtil.isTouch()||"touchstart"==h&&(h="mousedown"),$(e).bind(h,function(a){a.preventDefault();a.stopPropagation();g.handleBoundAction(a,b,e,c)}))}else this.throwError(d,e)};this.processAction=function(a,b){if(1<a.length){var e=a.split("/");if(1<e.length){e[1]=e[1].split(",");for(var c=0;c<e[1].length;c++)e[1][c]=DcUtil.stripWhiteSpace(e[1][c])}return{key:DcUtil.stripWhiteSpace(e[0]),params:e[1]}}this.throwError(a,b);return{key:"none",params:[]}};
this.handleBoundAction=function(d,b,e,c){if("call"==b.action.toLowerCase())if(c)a.views[c].callFunction(b.key,b.params,d);else if("function"==typeof a[b.key])a[b.key](b.params,d);else console.warn("exhausted tree looking for a function called "+b.key);else if("addclass"==b.action.toLowerCase())e=b.params+"",$(e).addClass(b.key);else if("removeclass"==b.action.toLowerCase())e=b.params+"",$(e).removeClass(b.key);else if("toggleclass"==b.action.toLowerCase())e=b.params+"",$(e).toggleClass(b.key);else if("emit"==
b.action.toLowerCase()){e=1;c=0;var g=!1;b.params[0]&&(-1<b.params[0].indexOf("-")?(c=b.params[0].split("-"),e=parseInt(c[0]),c=parseInt(c[1])):e=parseInt(b.params[0]));b.params[2]&&(g="target"==b.params[2]?d.target:document.querySelector(b.params[2]));for(var h=0;h<e;h++){if(c){var f=b.params[3]?document.querySelectorAll(b.params[3]):document.querySelectorAll("."+b.key);if(f.length&&f.length>c)for(var l=f.length-c,k=0;k<l;k++)f[k].parentNode.removeChild(f[k])}a.addView(b.key,!1,g,!1,function(a){if(b.params[1]&&
"event"==b.params[1]){if(DcUtil.isTouch())var c=$(g).position().left,e=$(g).position().top,c=d.originalEvent.touches[0].pageX-c,e=d.originalEvent.touches[0].pageY-e;else c=$(g).position().left,e=$(g).position().top,c=d.pageX-c,e=d.pageY-e;$(a.domContainer).css({left:c,top:e});a.show()}})}}else"showview"==b.action.toLowerCase()?a.showView(b):"hideview"==b.action.toLowerCase()?a.views[b.key]?a.views[b.key].hide(b.params):this.throwError(b.key+" view not found, can't hide! did you maybe not specify the view key as the element ID?"):
"toggleview"==b.action.toLowerCase()&&(a.views[b.key]?a.views[b.key].isVisible?a.views[b.key].hide(b.params):a.views[b.key].show(b.params):a.addView(b.key,!0))};this.throwError=function(a,b){console.warn("ERROR, Skipped DClare string was:");console.warn(a);b&&console.warn(b)}},DcUtil={stripWhiteSpace:function(a){return jQuery.trim(a)},isTouch:function(){return!!("ontouchstart"in window)||!!("onmsgesturechange"in window)},cssCache:[],loadCSS:function(a,c){if(0>DcUtil.cssCache.indexOf(a)){var d=document.createElement("link");
d.type="text/css";d.rel="stylesheet";d.href=a;document.getElementsByTagName("head")[0].appendChild(d);DcUtil.cssCache.push(a);d=document.createElement("img");d.onerror=function(){c&&c()};d.src=a}else c&&c()}};
